### ISSUE TITLE
[COMPAT] Do a Barrel Roll Combatibilty 

### ISSUE THREAD

**Issue by Camawama** [AvacadoWizard120/CameraOverhaulForge#1]
This is actually a feature I requested on the original mod's issue page. I was hoping to see compatibility between Do a Barrel Roll and this mod.

Currently, flying with elytra is slightly buggy. Looking straight up or down causes the camera to snap around strange.

https://www.curseforge.com/minecraft/mc-mods/do-a-barrel-roll

**Comment by AvacadoWizard120** [comment]
Should I just see if Do a Barrel Roll is installed and then disable the elytra stuff?

**Comment by Camawama** [comment]
Is there a way you can disable the camera tilting only during Elytra flight with that mod installed?

**Comment by AvacadoWizard120** [comment]
> Is there a way you can disable the camera tilting only during Elytra flight with that mod installed?

YES! I can have a boolean variable (true/false) that is set at runtime which will check if that mod is installed and then I can put the flying code in an if statement that says if (modIsPresent == false) then run the flight tilting.

**Comment by AvacadoWizard120** [comment]
> Is there a way you can disable the camera tilting only during Elytra flight with that mod installed?

What do you think would be best?
I *could* simply disable all of the features of the mod when you're flying and have barrel roll installed.

Or I could go the route that is currently implemented in the [1-compat-do-a-barrel-roll-combatibilty](https://github.com/AvacadoWizard120/CameraOverhaulForge/tree/1-compat-do-a-barrel-roll-combatibilty) branch which is to only disable the strafing when flying if the mod is installed. I can release a .jar for you to test the current implementation just give me feedback please! (let me know if anything changed lmao)

**Comment by AvacadoWizard120** [comment]
https://github.com/AvacadoWizard120/CameraOverhaulForge/releases/tag/barrel-roll-compat

download the patch from the releases page.

**Comment by Camawama** [comment]
Sorry for the late response! I just finished moving into our new place. I will begin testing in a couple days!!

**Comment by Camawama** [comment]
Unfortunately, it didn't seem to solve my issue. I am expericncing problems when flying elytra and looking straight up or down. The camera movements are super wonky. I am wondering if there was any extra step I was meant to take when testing the patch (I simply replaced the jar file).

**Comment by AvacadoWizard120** [comment]
Replacing the jar would be just fine. I'm currently not home at the moment so I can't do a hotfix, but I'll be home within the next few days and I'll take a look at it.

**Comment by AvacadoWizard120** [comment]
> Unfortunately, it didn't seem to solve my issue. I am expericncing problems when flying elytra and looking straight up or down. The camera movements are super wonky. I am wondering if there was any extra step I was meant to take when testing the patch (I simply replaced the jar file).

I am finally home and will try to revisit this issue!

**Comment by AvacadoWizard120** [comment]
> Is there a way you can disable the camera tilting only during Elytra flight with that mod installed?

pretty sure it works now

**Comment by AvacadoWizard120** [comment]
Actually I'm stupid hold on
