### ISSUE TITLE
[Bug] Crash when spectating any mob in spectator mode

### ISSUE THREAD

**Issue by 3247332139** [AvacadoWizard120/CameraOverhaulForge#2]
Crash when spectating any non-player entity in spectator mode.
It had been fixed in fabric,but still happening in forge.
Check it: https://github.com/Mirsario/Minecraft-CameraOverhaul/pull/18

[crash-2024-05-09_22.06.41-client.txt](https://github.com/AvacadoWizard120/CameraOverhaulForge/files/15263422/crash-2024-05-09_22.06.41-client.txt)
[debug.log](https://github.com/AvacadoWizard120/CameraOverhaulForge/files/15263423/debug.log)

**Comment by AvacadoWizard120** [comment]
It seems like I already have that fix, but I'll look into this further and make sure everything is proper 👍. It might be fixed today, but I'm pretty busy these days.

**Comment by AvacadoWizard120** [comment]
> Crash when spectating any non-player entity in spectator mode. It had been fixed in fabric,but still happening in forge. Check it: [Mirsario#18](https://github.com/Mirsario/Minecraft-CameraOverhaul/pull/18)
> 
> [crash-2024-05-09_22.06.41-client.txt](https://github.com/AvacadoWizard120/CameraOverhaulForge/files/15263422/crash-2024-05-09_22.06.41-client.txt) [debug.log](https://github.com/AvacadoWizard120/CameraOverhaulForge/files/15263423/debug.log)

okay it turns out I *don't* have this fix. I know what to do I just have to get around to doing it! I'm going to be going away for about a week and probably won't have internet so we'll see when that comes out. If you feel like it, comment in here every now and then to make sure I don't forget lol

**Comment by 3247332139** [comment]
i created a PR to fix it: https://github.com/AvacadoWizard120/CameraOverhaulForge/pull/3
it should be work.
:)
